# drivers/tomtom/si4703/Makefile
#
# Makefile for the TomTom si4703 kernel module
# This driver handles switching from and to different 
# usb modes
#
# Copyright (C) 2008,2009 TomTom BV <http://www.tomtom.com/>
# Author: Guillaume Ballet <Guillaume.Ballet@tomtom.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.

obj-$(CONFIG_TOMTOM_SI4703)		+= fmr.o
fmr-y	= si4703.o si4703_attr.o si4703_subr.o

# EOF
