# drivers/tomtom/scp1000/Makefile
#
# Makefile for the TomTom SCP1000 module
#
# Copyright (C) 2007,2008 TomTom BV <http://www.tomtom.com/>
# Author: Jeroen Taverne <jeroen.taverne@tomtom.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.

obj-$(CONFIG_TOMTOM_SCP1000)		+= scp1000.o

# EOF
