# drivers/tomtom/Makefile
#
# Copyright (C) 2008 TomTom BV <http://www.tomtom.com/>
# Author: Kees Jongenburger <kees.jongenburger@tomtom.com>
#         Vincent Ruitenberg <vincent.ruitenberg@tomtom.com>
#         Jeroen Taverne <jeroen.taverne@tomtom.com>
#         Niels Langendorff <niels.langendorff@tomtom.com>
#         Benoit Leffray <benoit.leffray@tomtom.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.

obj-$(CONFIG_TOMTOM_POWER_BUTTON)	+= power_button/
obj-$(CONFIG_TOMTOM_APPLE_AUTH)		+= apple-auth/
obj-$(CONFIG_TOMTOM_VBUSMON)		+= vbusmon/
obj-$(CONFIG_TOMTOM_IDPINMON)		+= idpinmon/
obj-$(CONFIG_TOMTOM_USBMODE)		+= usbmode/
obj-$(CONFIG_TOMTOM_USB_MODE_LITE)	+= usb_mode_lite/
obj-$(CONFIG_TOMTOM_SI4711)		+= si4711/
obj-$(CONFIG_TOMTOM_ACTIVE_DOCK)	+= dock/
obj-$(CONFIG_TOMTOM_PMIC)		+= pmic/
obj-$(CONFIG_TOMTOM_SCP1000)		+= sensors/barometer/
obj-$(CONFIG_TOMTOM_TPS851)		+= sensors/lightsensor/
obj-$(CONFIG_TOMTOM_GADC)		+= gadc/
obj-$(CONFIG_TOMTOM_BATTERY)		+= battery/
obj-$(CONFIG_TOMTOM_BLUETOOTH_MODE)	+= bluetooth_mode/
obj-$(CONFIG_TOMTOM_GPRS_GENERIC)	+= gprs/
obj-$(CONFIG_TOMTOM_GPS)		+= gps/
obj-$(CONFIG_TOMTOM_FLIPFLOP)		+= flipflop/
obj-$(CONFIG_TOMTOM_NASHVILLE)		+= sound/
obj-$(CONFIG_TOMTOM_SI4703)		+= si4703/
obj-$(CONFIG_TOMTOM_LOW_DC_VCC)		+= low_dc_vcc/
obj-$(CONFIG_TOMTOM_MEM)		+= mem/
obj-$(CONFIG_TOMTOM_TILT_TS0001_L)	+= tilt/
obj-$(CONFIG_TOMTOM_MS5607)		+= sensors/ms5607/
obj-$(CONFIG_TOMTOM_KXR94)		+= sensors/kxr94/
obj-$(CONFIG_TOMTOM_EWTS98)		+= sensors/ewts98/
obj-$(CONFIG_TOMTOM_LIS3DH)		+= sensors/lis3dh/
obj-$(CONFIG_TOMTOM_L3GD20)		+= sensors/l3gd20/
obj-$(CONFIG_TOMTOM_I3G4250D)		+= sensors/i3g4250d/
obj-$(CONFIG_TOMTOM_LM26)		+= sensors/lm26/
obj-$(CONFIG_TOMTOM_CAN_MICRO)		+= can_micro/
obj-$(CONFIG_TOMTOM_USB_PSUPPLY)	+= usb_psupply/
obj-$(CONFIG_TOMTOM_PPS_DRIVER)		+= pps/
obj-$(CONFIG_TOMTOM_BCM4329)		+= bcm4329-bt/
obj-$(CONFIG_TOMTOM_BCM2070)		+= bcm2070/
obj-$(CONFIG_TOMTOM_SUICIDE_ALARM)	+= suicide_alarm/
