# drivers/tomtom/sensors/i3g4250d/Makefile
#
# Makefile for the STMicroelectronics I3G4250D Gyroscope driver
#
# Copyright (C) 2016 TomTom BV <http://www.tomtom.com/>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.

obj-$(CONFIG_TOMTOM_I3G4250D)		+= i3g4250d.o

# EOF
