# drivers/tomtom/sensors/ms5607/Makefile
#
# Makefile for the MS5607 Micro Altimeter Module

# Copyright (C) 2011 TomTom BV <http://www.tomtom.com/>
# Author: Matthias Kaehlcke <matthias.kaehlcke@tomtom.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.

obj-$(CONFIG_TOMTOM_MS5607)		+= ms5607.o

# EOF
