obj-m	+=	adv7180-omap3.o
 
all:
	make -C /home/maja/p4/platform/android/main/mydroid/kernel/kbuild.martin M=$(PWD) modules

clean:
	make -C /home/maja/p4/platform/android/main/mydroid/kernel/kbuild.martin M=$(PWD) clean
