# drivers/tomtom/Makefile
#
# Copyright (C) 2008 TomTom BV <http://www.tomtom.com/>
# Author: Kees Jongenburger <kees.jongenburger@tomtom.com>
#         Vincent Ruitenberg <vincent.ruitenberg@tomtom.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.

obj-$(CONFIG_TOMTOM_PMIC_LTC3555)	+= ltc3555-pmic.o
obj-$(CONFIG_TOMTOM_PMIC_LTC3577)	+= ltc3577-pmic.o ltc3577-regulator.o
obj-$(CONFIG_TOMTOM_PMU_BCM59040_USBMODE)	+= bcm59040_usbmode.o
