# drivers/tomtom/sensors/ewts98/Makefile
#
# Makefile for the Panasonic EWTS98 Angular Rate Sensor driver
#
# Copyright (C) 2011 TomTom BV <http://www.tomtom.com/>
# Author: Matthias Kaehlcke <matthias.kaehlcke@tomtom.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.

obj-$(CONFIG_TOMTOM_EWTS98)		+= ewts98.o

# EOF
