# drivers/tomtom/gps/Makefile
#
# Copyright (C) 2008 TomTom BV <http://www.tomtom.com/>
# Author: Benoit Leffray <benoit.leffray@tomtom.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.

obj-$(CONFIG_TOMTOM_GPS_CLASS_DEVICE)	+= gps.o
obj-$(CONFIG_TOMTOM_GPS_GENERIC_DRIVER)	+= tomtom_gps.o
