# drivers/tomtom/gprs/Makefile
#
# Copyright (C) 2008 TomTom BV <http://www.tomtom.com/>
# Author: Niels Langendorff <niels.langendorff@tomtom.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.

obj-$(CONFIG_TOMTOM_GPRS_GENERIC)	+= gprs_generic/
obj-$(CONFIG_TOMTOM_GPRS_FARO)	+= faro/
