# drivers/tomtom/sensors/l3gd20/Makefile
#
# Makefile for the STMicroelectronics L3GD20 Gyroscope driver
#
# Copyright (C) 2013 TomTom BV <http://www.tomtom.com/>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.

obj-$(CONFIG_TOMTOM_L3GD20)		+= l3gd20_gyr.o

# EOF
