# drivers/tomtom/can_micro/Makefile
# 
# Copyright (C) 2009 TomTom BV <http://www.tomtom.com/>
# Author: Bert Janssen <bert.janssen@tomtom.com>
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#

obj-$(CONFIG_TOMTOM_CAN_MICRO)	+= can_micro.o
