#ifndef __PLAT_MENDOZA_H__
#define __PLAT_MENDOZA_H__

/* Define the virtual gpio base after the last of the physical gpios */
#define MENDOZA_VGPIO_BASE	400	/* Virtual gpio base */

enum mendoza_vgpio_pins {
	// VGPIO0
	TT_VGPIO0_BASE = MENDOZA_VGPIO_BASE,

	TT_VGPIO_PU_I2C0 = TT_VGPIO0_BASE,
	TT_VGPIO_PU_I2C1,
	TT_VGPIO_BOOT_DEV0,
	TT_VGPIO_SD_PWR_EN,
	TT_VGPIO_BARRACUDA_CS,
	TT_VGPIO_BACKLIGHT_EN,
	TT_VGPIO_LCM_RESET,
	TT_VGPIO_ON_OFF,
	TT_VGPIO_RFS_BOOT_CLK,
	TT_VGPIO_RFS_BOOT_Q,
	TT_VGPIO_USB_HOST_DETECT,
	TT_VGPIO_GPS_STANDBY, 
	TT_VGPIO_GPS_RESET,
	TT_VGPIO_BT_RST,
	TT_VGPIO_WALL_ON,
	TT_VGPIO_ID_PIN,
	TT_VGPIO_SD_CD,
	TT_VGPIO_SD_BASE,
	TT_VGPIO_SD_BOOT_BASE,
	TT_VGPIO_MIC_STBY,
	TT_VGPIO_L3_MODE,
	TT_VGPIO_GPS_1PPS,
	TT_VGPIO_GPS_CS,
	TT_VGPIO_PWR_KILL,
	TT_VGPIO_USB_3V3_ON,
	TT_VGPIO_USB_1V2_ON,
	TT_VGPIO_DOCK_RESET,
	TT_VGPIO_DOCK_DET0,
	TT_VGPIO_DOCK_DET1,
	TT_VGPIO_ACCESSORY_PWR_EN,
	TT_VGPIO_DOCK_DET_PWR,
	TT_VGPIO_DOCK_FM_INT,
	TT_VGPIO_DOCK_I2C_EN,
	TT_VGPIO_HPDETECT,
	TT_VGPIO_HRESET,
	TT_VGPIO_CHARGING,
	TT_VGPIO_DOCK_TX_SOC_RX,
	TT_VGPIO_MIC_RESET,
	TT_VGPIO_MUTE,
	TT_VGPIO_LCM_ID,
	TT_VGPIO_TP_IRQ,
	TT_VGPIO_TP_RESET,
	TT_VGPIO_TP_PWR,
	TT_VGPIO_DR_PWR_EN,
	TT_VGPIO_KXR94_CS,
	TT_VGPIO_BARO_CS,
	TT_VGPIO_TILT_PWR,
	TT_VGPIO_TILT_OUT,
	TT_VGPIO_DISP_ON,	

	TT_VGPIO_GSM_SYS_EN,
	TT_VGPIO_GSM_SYS_RST,
	TT_VGPIO_LCM_CS,
	TT_VGPIO_LCM_PWR_EN,
	TT_VGPIO_CODEC_PWR_EN,
	TT_VGPIO_AMP_PWR_EN,
	TT_VGPIO_MIC_AMP_EN,
	TT_VGPIO_LCD_SPI_CS,
	TT_VGPIO_LCD_SPI_SDI,
	TT_VGPIO_LCD_SPI_SCL,
	TT_VGPIO_EEPROM_WP,

	/* Bluetooth WiFi combo */
	TT_VGPIO_WIFI_RST,
	TT_VGPIO_BT_WAKE,
	TT_VGPIO_BT_HOST_WAKE,
	TT_VGPIO_BT_EN,
	TT_VGPIO_WIFI_EN,
	TT_VGPIO_WIFI_WAKE,

	// VGPIO1
	TT_VGPIO1_BASE,
};

#endif
