# Makefile for the LM26 temperature sensor

# Copyright (C) 2011 TomTom BV <http://www.tomtom.com/>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.

obj-$(CONFIG_TOMTOM_LM26)		+= lm26.o

# EOF
