#################################################
# Makefile for G2D on S3C6410
# 2008 (C) Samsung Electronics
# Author : joghun.han <jonghun.han@samsung.com>
#################################################

obj-$(CONFIG_VIDEO_G2D)	+= fimg2d_3x.o
