# drivers/tomtom/apple_auth/Makefile
#
# Makefile for the TomTom usbmode kernel module
# This driver handles switching from and to different
# usb modes
# 
# Copyright (C) 2007,2008 TomTom BV <http://www.tomtom.com/>
# Author: Carl Parsons <carl.parsons@tomtom.com>
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#

# Apple Authentication chip
obj-$(CONFIG_TOMTOM_APPLE_AUTH) += apple_auth.o
