# drivers/tomtom/sound/Makefile
#
# Copyright (C) 2009 TomTom BV <http://www.tomtom.com/>
# Author: Niels Langendorff <niels.langendorff@tomtom.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.

obj-$(CONFIG_TOMTOM_NASHVILLE_SCENARI)			+= nashville.o
obj-$(CONFIG_TOMTOM_NASHVILLE_SCENARI_DUMMY)		+= dummy.o
obj-$(CONFIG_TOMTOM_NASHVILLE_SCENARI_ADAU1761)		+= adau1761.o
obj-$(CONFIG_TOMTOM_NASHVILLE_SCENARI_BCM4760)		+= bcm4760_alc5627.o bcm4760_eua2011.o
obj-$(CONFIG_TOMTOM_NASHVILLE_SCENARI_WM8990)		+= wm8990.o
obj-$(CONFIG_TOMTOM_NASHVILLE_SCENARI_S5M8751)		+= s5m8751.o
obj-$(CONFIG_TOMTOM_NASHVILLE_SCENARI_TLV320ADC3101)	+= tlv320adc3101.o
obj-$(CONFIG_TOMTOM_NASHVILLE_SCENARI_TWL4030)      	+= twl4030.o
obj-$(CONFIG_TOMTOM_NASHVILLE_SCENARI_UDA1334)      	+= uda1334.o
