obj-$(CONFIG_VIDEO_FIMC)	+= fimc/
obj-$(CONFIG_VIDEO_JPEG_V2)	+= jpeg_v2/
obj-$(CONFIG_VIDEO_ROTATOR)	+= rotator/
obj-$(CONFIG_VIDEO_TV20)        += tv20/
obj-$(CONFIG_VIDEO_G2D)		+= g2d/
obj-$(CONFIG_VIDEO_POST)         += post/
obj-$(CONFIG_VIDEO_MALI400MP)   += mali/
EXTRA_CFLAGS += -Idrivers/media/video

