# drivers/tomtom/sensors/kxr94/Makefile
#
# Makefile for the Kionix KXR94 Accelerometer driver
#
# Copyright (C) 2010 TomTom BV <http://www.tomtom.com/>
# Author: Matthias Kaehlcke <matthias.kaehlcke@tomtom.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.

obj-$(CONFIG_TOMTOM_KXR94)		+= kxr94.o

# EOF
