# drivers/tomtom/pm/Makefile
#
# Makefile for the TomTom PPS driver.
# 
# Copyright (C) 2010 TomTom BV <http://www.tomtom.com/>
# Author: Rein Achten <rein.achten@tomtom.com>
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#

obj-$(CONFIG_TOMTOM_PPS_DRIVER) += pps.o
