# 
# Copyright (C) 2009 TomTom BV <http://www.tomtom.com/>
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#

obj-$(CONFIG_TOMTOM_VBUSMON_BCM59040_USBSTAT)	+= bcm59040_usbstat.o
obj-$(CONFIG_TOMTOM_VBUSMON)			+= vbusmon.o
obj-$(CONFIG_TOMTOM_GPIO_VBUSMON)	+= gpio_vbusmon.o
