# drivers/tomtom/gadc/Makefile
#
# Makefile for the TomTom GADC module
#
# Copyright (C) 2007,2008 TomTom BV <http://www.tomtom.com/>
# Author: Jeroen Taverne <jeroen.taverne@tomtom.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.

obj-$(CONFIG_TOMTOM_GADC_TITAN2)	+= titan2_gadc.o
obj-$(CONFIG_TOMTOM_GADC_SEOUL)		+= seoul_gadc.o
obj-$(CONFIG_TOMTOM_GADC_GENERIC)	+= gadc.o

# EOF
