# drivers/tomtom/sensors/lis3dh/Makefile
#
# Makefile for the STMicroelectronics LIS3DH Accelerometer driver
#
# Copyright (C) 2010 TomTom BV <http://www.tomtom.com/>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.

KBUILD_CFLAGS += -O0
obj-$(CONFIG_TOMTOM_LIS3DH)		+= lis3dh_acc.o

# EOF
